### ISSUE TITLE
Python version: spsolve() never used when alpha=0

### ISSUE THREAD

**Issue by sdmccabe** [cdebacco/SpringRank#2]
If alpha is set to zero, `scipy.solve.linalg.spsolve()` is never reached in the try/except block because of line 64:

```python
linalg.cond(x) < 1/sys.float_info.epsilon
```
So, in the demo dataset I believe `spsolve()` should be used instead of `bigcstab()`, but the latter is used anyway. If the line is removed (it doesn't seem to do anything), or changed to 
```python
np.linalg.cond(A.todense()) < 1/sys.float_info.epsilon
```
and `import sys` is added to the beginning of the file, it should work. 

If I do this, the test program uses `spsolve()` instead, though the results are essentially unchanged.

**Comment by cdebacco** [comment]
Hi Stefan,

nice catch!
I just added an updated version removing the try/except loop.
Now it should just use spsolve() straight.
Thanks!

Caterina

2018-07-23 23:31 GMT+02:00 Stefan McCabe <notifications@github.com>:
