### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by sdmccabe** [cdebacco/SpringRank#3]
[On Twitter](https://twitter.com/DanLarremore/status/1021442939380092929), Dan Larremore asked if anyone wanted to code up an R version. I hacked together a fairly crude port of the Python version of the code using `igraph` that seems to produce correct-looking output on the faculty hiring network. 

```r
spring_rank <- function(A, alpha, l0, l1, shift = TRUE) {
  N <- dim(A)[1]
  k_in <- colSums(A)
  k_out <- rowSums(A)
  One <- rep(1, N)
  C <- A + t(A)

  D1 <- matrix(0, ncol = N, nrow = N)
  D2 <- matrix(0, ncol = N, nrow = N)

  for (i in 1:N) {
    D1[i, i] <- k_out[i] + k_in[i]
    D2[i, i] <- l1 * (k_out[i] - k_in[i])
  }

  if (alpha != 0) {
    print("assuming invertible matrix")

    B = One * l0 + D2 %*% One
    A_ = alpha * diag(nrow = N, ncol = N) + D1 - C

    solvable = class(try(solve(A_, B), silent = T)) == "matrix"
    if (solvable)
    {
      print("using solve")
      rank <- solve(A_, B)
    } else {
      print("using bigcstab")
      rank <- Rlinsolve::lsolve.bicgstab(A_, B, verbose = F)
      rank <- rank$x
    }

    if (shift) {
      rank <- rank - min(rank)
    }
    
    names(rank) <- colnames(A)

  } else {
    print("fixing a rank degree of freedom")
    C <- C +
      matrix(rep(A[N,] , times = N),
             ncol = N,
             nrow = N,
             byrow = T) +
      matrix(rep(A[, N], times = N),
             ncol = N,
             nrow = N,
             byrow = T)

    D3 <- matrix(0, N, N)
    for (i in 1:N) {
      D3[i, i] <- l1 * (k_out[N] - k_in[N])
    }

    B <- D2 %*% One + D3 %*% One
    A_ <- D1 - C

    solvable <- class(try(solve(A_, B), silent = T)) == "matrix"
    if (solvable)
    {
      print("using solve")
      rank <- solve(A_, B)
    } else {
      print("using bigcstab")
      rank <- Rlinsolve::lsolve.bicgstab(A_, B)$x
    }
    
    if (shift) {
      rank <- rank - min(rank)
    }
    
    names(rank) <- colnames(A)
  }
  return(rank)
}
```
So, if run with:
```r
library(igraph)
library(readr)
library(Rlinsolve)

df <- read_delim("US_CS_adjacency.dat",
             delim = " ",
             col_names = c("i", "j", "weight"))

G <- graph.data.frame(df)
A <- as.matrix(as_adjacency_matrix(G, attr = "weight"))

alpha <- 0.0
l0 <- 1.0
l1 <- 1.0

r <- spring_rank(A, alpha, l0, l1)
round(rev(r[order(r)]), 3)
```

The output is something like:
```
2 2.423
1 2.416
3 2.390
...
195 0.039
197 0.003
205 0.000
```
I've experimented with tweaking alpha, l1, and l2, and the code doesn't seem to blow up, but I haven't tried other graphs. One minor detail is that, because igraph and networkx return differently ordered adjacency matrices, the row/column used to create `C` if alpha=0 are not the same. 

If there's interest, I think I can also hack together an R equivalent for the generative model over the next day or two and add some comments, etc.

**Comment by dblarremore** [comment]
This looks great. I am unable to check the correctness of the R code, but just from reading, a few questions:

1. Is the _if (solvable)_ check for the alpha=0 case attempting to see if the system can be inverted? If so, I think that that condition should never be met, since the system is a linear-Laplacian system, and therefore never invertible. 

2. In general, I would favor the iterative solvers, even when alpha > 0, simply because they will far more easily accommodate large matrices. 

If the ranks are identical when setting min(rank)=0 using the Python/MATLAB and the R version, I think you should submit a pull request and we can get this up! Thanks for the efforts!

**Comment by cdebacco** [comment]
I just fixed it and uploaded the new version, thanks Stefan!

2018-07-24 1:11 GMT+02:00 Daniel Larremore <notifications@github.com>:

**Comment by sdmccabe** [comment]
As for the iterative solver, I was trying to ape the structure of the Python program as much as possible to keep things simple. Would just using `bicgstab` everywhere address the concerns about large matrices?

**Comment by dblarremore** [comment]
Yeah, this seems fine to use, if that's what you mean?

https://www.rdocumentation.org/packages/Rlinsolve/versions/0.2.0/topics/lsolve.bicgstab

That will allow the algorithm to scale nicely when there are 500 or more
nodes.

If you code it up, test it, and submit another pull request, that would be
awesome. And, again, thanks for your help. I'm 95% clueless about R stuff!
